"CORRECTION":
    - "Truth": null
    - "Reco":
          - "Primary":
                - "equal": true
          - "Generator":
                - "equal": 1
          - "SignalParticleE":
                - "absbetween": [4, 20]
          - "NeutronK":
                - "equal": 0

"CALIBRATION":
    - "Truth": null
    - "Reco":
          - "Primary":
                - "equal": true
          - "Generator":
                - "equal": 1
          - "SignalParticleE":
                - "absbetween": [4, 20]
          - "NeutronK":
                - "equal": 0
          - "NHits":
                - "bigger": 2

"DISCRIMINATION":
    - "Truth": null
    - "Reco":
          - "Primary":
                - "equal": true
          - "Generator":
                - "equal": 1
          - "SignalParticleE":
                - "absbetween": [4, 20]
          - "NeutronK":
                - "equal": 0
          - "NHits":
                - "bigger": 2

"RECONSTRUCTION":
    - "Truth": null
    - "Reco":
          - "Primary":
                - "equal": true
          - "Generator":
                - "equal": 1
          - "SignalParticleE":
                - "absbetween": [4, 30]
          - "NHits":
                - "bigger": 2

"SMEARING":
    - "Truth": null
    - "Reco":
          - "Primary":
                - "equal": true
          - "Generator":
                - "equal": 1
          - "SignalParticleE":
                - "absbetween": [4, 30]
          - "NHits":
                - "bigger": 2

"ANALYSIS":
    - "Truth": null
    - "Reco":
          - "Primary":
                - "equal": true
          - "NHits":
                - "bigger": 2

"FIDUCIALIZATION":
    - "Truth": null
    - "Reco":
          - "RecoX":
                - "absbetween": [100, 260]
          - "RecoY":
                - "absbetween": [100, 500]
          - "RecoZ":
                - "absbetween": [10, 1390]
