"TRUTH":
        - "Config": null
        - "Truth":
                  - "Config":
                            - "equal": true
                  - "Generator":
                            - "equal": 1
                  - "SignalParticleK":
                            - "absbetween": [0, 30]
        - "Reco": null

"CORRECTION":
        - "Config": null
        - "Truth": null
        - "Reco":
                  - "Primary":
                            - "equal": true
                  - "Generator":
                            - "equal": 1
                  - "SignalParticleK":
                            - "absbetween": [0, 20]
                  - "NeutronK":
                            - "equal": 0

"CALIBRATION":
        - "Config": null
        - "Truth": null
        - "Reco":
                  - "Primary":
                            - "equal": true
                  - "Generator":
                            - "equal": 1
                  - "SignalParticleK":
                            - "absbetween": [0, 20]
                  - "NeutronK":
                            - "equal": 0

"DISCRIMINATION":
        - "Config": null
        - "Truth": null
        - "Reco":
                  - "Primary":
                            - "equal": true
                  - "Generator":
                            - "equal": 1

                  - "SignalParticleK":
                            - "absbetween": [0, 20]

                  - "NeutronK":
                            - "equal": 0

"RECONSTRUCTION":
        - "Config": null
        - "Truth": null
        - "Reco":
                  - "Primary":
                            - "equal": true
                  - "Generator":
                            - "equal": 1

                  - "SignalParticleK":
                            - "absbetween": [0, 30]

"SMEARING":
        - "Config": null
        - "Truth": null
        - "Reco":
                  - "Primary":
                            - "equal": true
                  - "Generator":
                            - "equal": 1

                  - "SignalParticleK":
                            - "absbetween": [0, 30]

"ANALYSIS":
        - "Config": null
        - "Truth": null
        - "Reco":
                  - "Primary":
                            - "equal": true
                  - "Generator":
                            - "equal": 1
                  - "SignalParticleK":
                            - "absbetween": [0, 20]

"FIDUCIALIZATION":
        - "Config": null
        - "Truth": null
        - "Reco":
                  #   - "MainParentZ":
                  #             - "between": [5, 1395]
                  #   - "MainParentX":
                  #             - "outside": [-5, 5]
                  - "RecoX":
                            - "absbetween": [50, 310]
                  - "RecoY":
                            - "absbetween": [50, 550]
                  - "RecoZ":
                            - "absbetween": [10, 1390]
