"""
run_signal.py — Signal characterisation pipeline
=================================================
Reads pre-computed MARLEY Neutrino_CC_Fraction DataFrames (saved by
TruthMarleyStacked.ipynb or equivalent) and produces signal characterisation
plots without requiring raw ROOT file access.

Stages (per config/name pair)
------------------------------
  1  fractional energy   Stacked bar of mean daughter kinetic energy fraction
                         per particle type vs neutrino energy.
  2  kinematic threshold line_plot.py --plot_type kinematic_threshold
                         (1 - Σ f_i) × E_nu  — energy going to nuclear recoil.

Input — DataFrames
------------------
  {data}/marley/stacked/{config}/{name}/
    {config}_{name}_Neutrino_CC_Fraction.pkl
      Generated by TruthMarleyStacked.ipynb. Columns:
        SignalParticleK, TSignalSumK, TMarleyParticle, TMarleyColor,
        TSignalSumPDG, PDG, Config, Name

Outputs — figures
-----------------
  {images}/marley/stacked/
    {config}_{name}_Neutrino_CC_Fraction.png    — fractional energy stacked bar
    {config}_{name}_KinematicThreshold.png      — via line_plot.py

Run examples
------------
  # Single config:
  python3 src/pipelines/run_signal.py \\
      --config hd_1x2x6 --name marley_official

  # Multiple configs:
  python3 src/pipelines/run_signal.py \\
      --config hd_1x2x6 vd_1x8x14 --name marley_official

  # DataFrames only, skip figures:
  python3 src/pipelines/run_signal.py \\
      --config hd_1x2x6 --name marley_official --no-plot
"""

import os
import sys
import subprocess
from typing import List, Optional

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../")))

from lib import *

# ── CLI ──────────────────────────────────────────────────────────────────────
_analysis_info = load_analysis_info(str(root))

parser = argparse.ArgumentParser(
    description="Signal characterisation pipeline — reads MARLEY CC fraction DataFrames"
)
parser.add_argument(
    "--config",
    nargs="+",
    type=str,
    default=["hd_1x2x6"],
    help="Detector config short name(s) matching data/marley/stacked/ subdirs.",
)
parser.add_argument(
    "--name",
    nargs="+",
    type=str,
    default=["marley_official"],
    help="Sample name(s) matching the saved Neutrino_CC_Fraction DataFrame.",
)
parser.add_argument(
    "--rewrite",
    action=argparse.BooleanOptionalAction,
    default=True,
)
parser.add_argument(
    "--plot",
    action=argparse.BooleanOptionalAction,
    default=True,
)
parser.add_argument(
    "--debug",
    action=argparse.BooleanOptionalAction,
    default=False,
)

args = parser.parse_args()

# ── Paths ─────────────────────────────────────────────────────────────────────
_data_root  = f"{root}/output/data/marley/stacked"
_image_root = f"{root}/output/images/marley/stacked"
os.makedirs(_image_root, exist_ok=True)

# ── Helpers ───────────────────────────────────────────────────────────────────

def _subprocess_env() -> dict:
    env = os.environ.copy()
    chrome_exe = os.path.join(str(root), ".chrome", "chrome-linux64", "chrome")
    if os.path.isfile(chrome_exe) and "BROWSER_PATH" not in env:
        env["BROWSER_PATH"] = chrome_exe
    return env


def _run(cmd: List[str], label: str, stop_on_error: bool = True):
    rendered = " ".join(cmd)
    rprint(f"\n[green][CMD][/green] {rendered}")
    result = subprocess.run(cmd, check=False, env=_subprocess_env())
    if result.returncode != 0 and stop_on_error:
        raise SystemExit(
            f"{label} failed with exit code {result.returncode}.\nCommand: {rendered}"
        )


def _rw()    -> str: return "--rewrite"    if args.rewrite else "--no-rewrite"
def _debug() -> str: return "--debug"      if args.debug   else "--no-debug"
def _plot()  -> str: return "--plot"       if args.plot    else "--no-plot"


# ── Stage 1: Fractional energy stacked bar ────────────────────────────────────

def run_fractional_energy(config: str, name: str):
    """
    Stacked bar of mean daughter kinetic energy fraction per particle type.

    Reads {config}_{name}_Neutrino_CC_Fraction.pkl and plots:
      y = TSignalSumK (fraction of neutrino energy, per particle type)
      x = SignalParticleK (true neutrino energy, MeV)
    """
    pkl = f"{_data_root}/{config}/{name}/{config}_{name}_Neutrino_CC_Fraction.pkl"
    if not os.path.exists(pkl):
        rprint(
            f"[yellow][WARNING][/yellow] Neutrino_CC_Fraction pkl not found: {pkl}\n"
            "  Run TruthMarleyStacked.ipynb first to generate input data."
        )
        return

    df = pd.read_pickle(pkl)
    rprint(
        f"  [green][OK][/green] Loaded Neutrino_CC_Fraction "
        f"({len(df)} rows, config={config}, name={name})"
    )

    plot_df = df[df.get("TMarleyColor", pd.Series("grey", index=df.index)) != "grey"].copy()
    plot_df["SignalParticleK"] = plot_df["SignalParticleK"].astype(float)
    plot_df["TSignalSumK"]     = plot_df["TSignalSumK"].astype(float)

    pdg_colors = list(
        get_pdg_color(plot_df["TSignalSumPDG"].unique().tolist()).values()
    )

    fig = px.bar(
        plot_df,
        x="SignalParticleK",
        y="TSignalSumK",
        color="TMarleyParticle",
        color_discrete_sequence=pdg_colors,
        barmode="stack",
    )
    fig = format_coustom_plotly(fig, title="CC Neutrino — Ar Interaction")
    fig.update_yaxes(title_text="Average Fractional Truth Particle Energy")
    fig.update_xaxes(title_text="True Neutrino Energy (MeV)")
    fig.update_layout(legend=dict(title="Daughter particle"))

    if args.plot:
        save_figure(
            fig, _image_root,
            config=None, name=None, subfolder=None,
            filename=f"{config}_{name}_Neutrino_CC_Fraction",
            rm=args.rewrite, debug=args.plot,
        )
        rprint(f"  [green][OK][/green] Fractional energy figure saved")


# ── Stage 2: Kinematic threshold via line_plot.py ─────────────────────────────

def run_kinematic_threshold(config: str, name: str):
    _run(
        [
            "python3", f"{root}/src/physics/common/line_plot.py",
            "--plot_type", "kinematic_threshold",
            "--config", config,
            "--name", name,
            _rw(), _debug(), _plot(),
        ],
        label="line_plot.py kinematic_threshold",
        stop_on_error=False,
    )


# ── Main loop ─────────────────────────────────────────────────────────────────

for _config, _name in product(args.config, args.name):
    rprint(f"\n[bold magenta]{'═'*60}[/bold magenta]")
    rprint(f"[bold magenta]  config={_config}  name={_name}[/bold magenta]")
    rprint(f"[bold magenta]{'═'*60}[/bold magenta]")

    rprint("\n[bold cyan]── Stage 1: Fractional daughter energy ──[/bold cyan]")
    run_fractional_energy(_config, _name)

    rprint("\n[bold cyan]── Stage 2: Kinematic threshold ──[/bold cyan]")
    run_kinematic_threshold(_config, _name)

rprint("\n[bold green]run_signal complete.[/bold green]")
