"TRUTH":
        - "Config": null
        - "Truth":
                - "Config":
                        - "equal": true
                - "Generator":
                        - "equal": 1
                - "SignalParticleK":
                        - "absbetween": [0, 30]
        - "Reco": null

"CORRECTION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Primary":
                        - "equal": true
                - "Generator":
                        - "equal": 1
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":
                        - "equal": 0
                - "Charge":
                        - "bigger": 100

"CALIBRATION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Primary":
                        - "equal": true
                - "Generator":
                        - "equal": 1
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":
                        - "equal": 0
                - "CorrectedCharge":
                        - "bigger": 150

"DISCRIMINATION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Primary":
                        - "equal": true
                - "Generator":
                        - "equal": 1
                - "SignalParticleK":
                        - "absbetween": [0, 20]
                - "CorrectedCharge":
                        - "bigger": 150

"RECONSTRUCTION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Primary":
                        - "equal": true
                - "Generator":
                        - "equal": 1
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "CorrectedCharge":
                        - "bigger": 150

"SMEARING":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Primary":
                        - "equal": true
                - "Generator":
                        - "equal": 1
                - "SignalParticleK":
                        - "absbetween": [0, 30]

"ANALYSIS":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Primary":
                        - "equal": true
                - "Generator":
                        - "equal": 1
                - "SignalParticleK":
                        - "absbetween": [0, 30]
