"TRUTH":
        - "Config": null
        - "Truth":
                - "Config":
                        - "equal": true
                - "Generator":
                        - "equal": 1
                - "SignalParticleK":
                        - "absbetween": [0, 30]
        - "Reco": null

"CORRECTION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Generator":
                        - "equal": 1
                - "Primary":
                        - "equal": true
                - "TrueMain":
                        - "equal": True
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":
                        - "equal": 0
                - "SignalParticleK":
                        - "absbetween": [0, 30]

"CALIBRATION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Generator":
                        - "equal": 1
                - "Primary":
                        - "equal": true
                - "TrueMain":
                        - "equal": True
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":
                        - "equal": 0
                - "SignalParticleK":
                        - "absbetween": [0, 30]

"DISCRIMINATION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Generator":
                        - "equal": 1
                - "Primary":
                        - "equal": true
                - "TrueMain":
                        - "equal": True
                - "SignalParticleK":
                        - "absbetween": [0, 30]

"RECONSTRUCTION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Generator":
                        - "equal": 1
                - "Primary":
                        - "equal": true
                - "TrueMain":
                        - "equal": True
                - "SignalParticleK":
                        - "absbetween": [0, 30]

"SMEARING":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Generator":
                        - "equal": 1
                - "Primary":
                        - "equal": true
                - "TrueMain":
                        - "equal": True
                - "SignalParticleK":
                        - "absbetween": [0, 30]

"ANALYSIS":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "Primary":
                        - "equal": true
                - "Generator":
                        - "equal": 1
                - "SignalParticleK":
                        - "absbetween": [0, 30]
