"TRUTH":
        - "Config": null
        - "Truth":
                - "Config":
                        - "equal": true
                - "Generator":
                        - "equal": 1
                - "SignalParticleK":
                        - "absbetween": [0, 30]
        - "Reco": null

"CORRECTION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "SignalParticleE":
                        - "absbetween": [0, 30]
                - "Generator":
                        - "equal": 1
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":
                      - "equal": 0
                - "Charge":
                        - "bigger": 250    

"CALIBRATION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "SignalParticleE":
                        - "absbetween": [0, 30]
                - "Generator":
                        - "equal": 1
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":
                        - "equal": 0
                - "CorrectedCharge":
                        - "bigger": 300

"DISCRIMINATION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "SignalParticleE":
                        - "absbetween": [0, 30]
                - "Generator":
                        - "equal": 1
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":
                        - "equal": 0
                - "CorrectedCharge":
                        - "bigger": 300        

"RECONSTRUCTION":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "SignalParticleE":
                        - "absbetween": [0, 30]
                - "Generator":
                        - "equal": 1
                - "NeutronK":
                        - "equal": 0
                - "ProtonK":
                        - "equal": 0
                - "CorrectedCharge":
                        - "bigger": 300

"SMEARING":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "SignalParticleE":
                        - "absbetween": [0, 30]
                - "Generator":
                        - "equal": 1

"ANALYSIS":
        - "Config": null
        - "Truth": null
        - "Reco":
                - "SignalParticleK":
                        - "absbetween": [0, 30]
                - "Generator":
                        - "equal": 1